#!/bin/bash
# Quick Strapi Deployment Setup for Railway

echo "🚀 Setting up Strapi deployment on Railway..."
echo ""
echo "Railway is a modern deployment platform with a generous free tier."
echo "This script will help you deploy your local Strapi instance to production."
echo ""

echo "📋 Prerequisites:"
echo "1. Sign up at https://railway.app with your GitHub account"
echo "2. Install Railway CLI: npm install -g @railway/cli"
echo "3. Your local Strapi project in the vortex-cms directory"
echo ""

echo "🔧 Deployment Steps:"
echo ""
echo "1. Navigate to your Strapi directory:"
echo "   cd vortex-cms"
echo ""
echo "2. Login to Railway:"
echo "   railway login"
echo ""
echo "3. Create new Railway project:"
echo "   railway new"
echo ""
echo "4. Deploy your Strapi app:"
echo "   railway up"
echo ""
echo "5. Add environment variables in Railway dashboard:"
echo "   - DATABASE_URL (Railway will provide PostgreSQL)"
echo "   - JWT_SECRET (generate with: openssl rand -base64 32)"
echo "   - API_TOKEN_SALT (generate with: openssl rand -base64 32)"
echo "   - ADMIN_JWT_SECRET (generate with: openssl rand -base64 32)"
echo "   - APP_KEYS (generate 4 keys with: openssl rand -base64 32)"
echo ""
echo "6. Get your Railway app URL and API token:"
echo "   - URL will be like: https://your-app-name.railway.app"
echo "   - Create API token in Strapi admin > Settings > API Tokens"
echo ""
echo "7. Update Vercel environment variables:"
echo "   - VITE_STRAPI_URL=https://your-app-name.railway.app"
echo "   - VITE_STRAPI_API_TOKEN=your-new-production-token"
echo ""

echo "🌟 Alternative: Quick Test with ngrok"
echo ""
echo "For immediate testing, you can expose your local Strapi with ngrok:"
echo ""
echo "1. Install ngrok: https://ngrok.com/download"
echo "2. Start your local Strapi: npm run develop"
echo "3. In another terminal: ngrok http 1338"
echo "4. Copy the https URL (like: https://abc123.ngrok.io)"
echo "5. Add to Vercel environment variables:"
echo "   - VITE_STRAPI_URL=https://abc123.ngrok.io"
echo "   - VITE_STRAPI_API_TOKEN=5477f8f25008fb9702b8052028b14842910b97dc8889824f283a78746868447adbc8aebb4b62ca44befc8a24dbad92b7728b345ebe77541a029dcb36d8e337f79109e597c940c7711bb170dd75aa1ca57e667de60a21967f424ef895044e69154fe87fb7887d9fc1c94bd11af68231cf1807ad7247f96c7f637c1d2fc2be267c"
echo ""

echo "⚡ Quick Start: Test with ngrok first, then deploy to Railway for permanent solution."